### ISSUE TITLE
US : configuration (pour controler le volume de la musique, des sons, fullscreen ou pas, touches, etc...)

### ISSUE THREAD

**Issue by Ormidales** [Ormidales/PTUT#21]
- [x] Créer un menu d'option
- [x] Ajouter le contrôle des volumes audios et musiques dans le menu option
- [x] Ajouter l'option fullscreen
- [ ] Ajouter les modifications des touches de contrôle du personnage

**Comment by Ormidales** [comment]
Tutoriel faciles à comprendre pour le fullscreen : 
[https://www.youtube.com/watch?v=QxU58uAcZDc](https://www.youtube.com/watch?v=QxU58uAcZDc)

**Comment by Ormidales** [comment]
Tutoriel facile pour comprendre le mapping des touches : 
[https://www.youtube.com/watch?v=TzlN0Rqf6jE](https://www.youtube.com/watch?v=TzlN0Rqf6jE)

**Comment by Ormidales** [comment]
Exemple de menu d'options : 
https://interfaceingame.com/screenshots/ruiner-audio/
https://interfaceingame.com/screenshots/ruiner-profil/

![Image](https://user-images.githubusercontent.com/46538211/216723365-98a00065-fa54-4e78-ad67-0155485fd875.png)
![Image](https://user-images.githubusercontent.com/46538211/216723572-37fded2c-a41d-4dc7-8d5c-b90336d6a0a0.png)
