### ISSUE TITLE
US : ennemi simple

### ISSUE THREAD

**Issue by Leushuis** [Ormidales/PTUT#42]
En tant que joueur, je souhaite affronter un ennemi afin de pouvoir le combattre.

- [ ] un ennemi est visible dans le wagon 
- [ ] l'ennemi peut mettre des dégâts au personnage en le touchant
- [ ] l'ennemi perd des points de vie quand le personnage l'attaque (10PV)

![Image](https://user-images.githubusercontent.com/72081603/223969050-389ab80f-bb90-43aa-bcd9-1e0cf2c5fe72.png)
