### ISSUE TITLE
US : map design gare

### ISSUE THREAD

**Issue by Leushuis** [Ormidales/PTUT#45]
En tant qu'utilisateur, je souhaite pouvoir me déplacer dans une map.

- [x] Une map est créée
- [x] Un détecteur est placé sur la map afin de faire une action (quitter,  prochain niveau)
- [x] Le joueur peut se déplacé librement sur la map
