### ISSUE TITLE
US : shop

### ISSUE THREAD

**Issue by Leushuis** [Ormidales/PTUT#46]
En tant qu'utilisateur, je souhaite pouvoir interagir avec un shop afin d'acheter des objets.

- [x] rentrer dans le shop 
- [x] visualiser les objets
- [x] afficher le prix de chaque objet
- [x] pouvoir choisir un objet
- [x] payer un objet si la somme des pièces est suffisantes
- [x] l'objet disparait ou n'est plus achetable
- [ ] l'objet est stocké dans un inventaire du personnage pour l'utilisé plus tard
