### ISSUE TITLE
US : map design plusieurs niveaux

### ISSUE THREAD

**Issue by Leushuis** [Ormidales/PTUT#50]
En tant qu'utilisateur, je souhaite pouvoir enchainer des niveaux élémentaires (wagon) différents.

Création de tileset pour chaque wagon

- [x] 3 tileset sont créés
- [x] 3 scenes sont créés (1 gare et 2 wagon) 
- [x] enchainements aléatoire des niveaux
