### ISSUE TITLE
US : animations personnage

### ISSUE THREAD

**Issue by Leushuis** [Ormidales/PTUT#72]
- [x] Animation de marche

- [x] Animation de mort

- [x] Animation de prise de dégât

- [x] Animation d'attaque
